import React from 'react';
import { LLM_ENDPOINT, getLlmModel } from './llmConfig.js';

/* ─── Optinio the Goblin ──────────────────────────────────────────
 * Clippy-style TV companion. Watches live game state and pops up
 * with LLM-generated one-liners (canned fallbacks if the LLM is
 * napping), spoken via tuned browser TTS. DM can disable him via
 * gameState.optinioEnabled.
 */

const PERSONA =
  'You are Optinio the Goblin, the comic-relief mascot of a family D&D game ' +
  'played by kids aged 8-13 and their dad. Personality: Claptrap from ' +
  'Borderlands meets Clippy — overconfident, dramatic, mostly useless, ' +
  'occasionally accidentally wise, obsessed with snacks and shiny things. ' +
  'Strictly kid-friendly. Reply with ONE punchy line, max 2 short sentences, ' +
  'no quotes, reacting to what just happened.';

// Generated by the campaign's own LLM — the pitch deck carries the same set.
const FALLBACK_OPINIONS = {
  crit: 'By my shiny ears, that was legendary!',
  fail: 'Oof, my eyes! That was spectacularly bad!',
  monsterDown: 'BONKED! Send that monster to the scrap heap!',
  heroDown: 'BONKED! Someone get that hero a bandage!',
  levelUp: 'Ooooh, sparkly new powers incoming!',
  quest: 'We did it, now where is my victory cookie?',
  puzzle: 'Uh oh, time to use those big, smart brains!',
  snack: 'Munch, crunch, heal, repeat!',
  scary: "I'm hiding behind this rock until the spooky stuff stops!",
  dragon: "Run away, it's a giant, fire-breathing lizard!",
  bored: "Is it nap time yet? I'm bored!",
};

const SCARY_SCENES = ['caves', 'bridge', 'ruins'];
const DRAGON_SCENES = ['peak'];
const COOLDOWN_MS = 45_000;
const BIG_EVENTS = ['crit', 'fail', 'quest', 'levelUp', 'monsterDown', 'heroDown', 'dragon'];
const AMBIENT_CHANCE = 0.55;
const IDLE_MS = 150_000;

async function generateOpinion(eventKey, context) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 7000);
  try {
    const response = await fetch(LLM_ENDPOINT, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      signal: controller.signal,
      body: JSON.stringify({
        model: getLlmModel(),
        messages: [
          { role: 'system', content: PERSONA },
          { role: 'user', content: `Just happened in the game: ${context}` },
        ],
        max_tokens: 60,
        temperature: 0.95,
        stream: false,
      }),
    });
    if (!response.ok) throw new Error(`LLM ${response.status}`);
    const data = await response.json();
    const text = data?.choices?.[0]?.message?.content?.trim();
    return text || FALLBACK_OPINIONS[eventKey];
  } catch {
    return FALLBACK_OPINIONS[eventKey];
  } finally {
    clearTimeout(timer);
  }
}

function speakAsGoblin(text) {
  if (!('speechSynthesis' in window)) return;
  // Don't cancel: if narration is mid-sentence we skip instead (see caller).
  const utterance = new SpeechSynthesisUtterance(text);
  utterance.pitch = 1.75; // squeaky
  utterance.rate = 1.15;  // motormouth
  const voices = window.speechSynthesis.getVoices();
  const voice =
    voices.find(v => v.lang.startsWith('en') && /google/i.test(v.name)) ||
    voices.find(v => v.lang.startsWith('en'));
  if (voice) utterance.voice = voice;
  window.speechSynthesis.speak(utterance);
}

export function GoblinOpinions({ gameState, campaignData }) {
  const [line, setLine] = React.useState(null);
  const prevRef = React.useRef(null);
  const lastShownRef = React.useRef(0);
  const busyRef = React.useRef(false);
  const idleTimerRef = React.useRef(null);

  const entityName = React.useCallback((id) => {
    const all = [...campaignData.characters, ...campaignData.monsters];
    return all.find(e => e.id === id)?.name || id;
  }, [campaignData]);

  const trigger = React.useCallback(async (eventKey, context) => {
    const now = Date.now();
    if (busyRef.current) return;
    if (now - lastShownRef.current < COOLDOWN_MS) return;
    if (!BIG_EVENTS.includes(eventKey) && Math.random() > AMBIENT_CHANCE) return;
    busyRef.current = true;
    lastShownRef.current = now;
    const text = await generateOpinion(eventKey, context);
    setLine(text);
    // Don't talk over DM narration TTS — bubble only in that case.
    if (!gameState.narration?.voiceId) speakAsGoblin(text);
    setTimeout(() => {
      setLine(null);
      busyRef.current = false;
    }, Math.max(5000, text.length * 90));
  }, [gameState.narration?.voiceId]);

  // ── Event detection against previous synced state ──
  React.useEffect(() => {
    const prev = prevRef.current;
    prevRef.current = {
      rollId: gameState.lastRoll?.id,
      levelUpId: gameState.levelUp?.id,
      toastId: gameState.toast?.id,
      puzzleId: gameState.activePuzzle?.puzzleId,
      sceneId: gameState.currentSceneId,
      hp: gameState.characterHp,
    };
    if (!prev) return; // first mount: learn state, stay quiet

    const roll = gameState.lastRoll;
    if (roll?.id && roll.id !== prev.rollId) {
      if (roll.d20 === 20) return void trigger('crit', `${roll.label} — a NATURAL 20!`);
      if (roll.d20 === 1) return void trigger('fail', `${roll.label} — a natural 1. Disaster.`);
    }

    if (gameState.levelUp?.id && gameState.levelUp.id !== prev.levelUpId) {
      return void trigger('levelUp',
        `${gameState.levelUp.characterName} just reached level ${gameState.levelUp.newLevel}!`);
    }

    if (gameState.toast?.id && gameState.toast.id !== prev.toastId) {
      if (gameState.toast.title === 'Yum!') return void trigger('snack', gameState.toast.message);
      if (gameState.toast.title === 'Quest Complete!') {
        return void trigger('quest', `Quest complete! ${gameState.toast.message}`);
      }
    }

    if (gameState.activePuzzle?.puzzleId && gameState.activePuzzle.puzzleId !== prev.puzzleId) {
      return void trigger('puzzle', 'A puzzle just appeared on the screen!');
    }

    if (gameState.currentSceneId !== prev.sceneId) {
      if (DRAGON_SCENES.includes(gameState.currentSceneId)) {
        return void trigger('dragon', 'The party just arrived at the dragon\'s peak!');
      }
      if (SCARY_SCENES.includes(gameState.currentSceneId)) {
        return void trigger('scary', 'The party just entered a dark, spooky place.');
      }
    }

    // Somebody hit 0 HP since last state
    if (prev.hp) {
      for (const [id, hp] of Object.entries(gameState.characterHp || {})) {
        if (hp === 0 && prev.hp[id] > 0) {
          const isMonster = campaignData.monsters.some(m => m.id === id);
          return void trigger(isMonster ? 'monsterDown' : 'heroDown',
            `${entityName(id)} just got BONKED (0 HP)!`);
        }
      }
    }
  }, [gameState, campaignData, trigger, entityName]);

  // ── Idle chatter ──
  React.useEffect(() => {
    clearTimeout(idleTimerRef.current);
    idleTimerRef.current = setTimeout(() => {
      trigger('bored', 'Nothing has happened for a few minutes. You are bored.');
    }, IDLE_MS);
    return () => clearTimeout(idleTimerRef.current);
  }, [gameState, trigger]);

  if (!line) return null;

  return (
    <div data-testid="goblin-opinion" className="fixed bottom-6 right-6 z-40 flex flex-col items-end gap-2 pointer-events-none animate-[goblinpop_.35s_steps(6)]">
      <div className="bg-white text-gray-900 border-4 border-black shadow-[5px_5px_0px_rgba(0,0,0,0.6)] px-5 py-3 max-w-md text-left relative">
        <p className="text-[9px] font-bold text-green-700 tracking-widest mb-1">OPTINIO THE GOBLIN SAYS:</p>
        <p className="text-sm leading-relaxed font-bold">{line}</p>
        <div className="absolute -bottom-4 right-8 border-8 border-transparent border-t-black" />
      </div>
      <img
        src="/pixel_goblin.png"
        alt="Optinio the Goblin"
        className="w-28 h-28 object-cover border-4 border-green-500 shadow-[6px_6px_0px_rgba(0,0,0,1)] animate-[goblinbob_.6s_steps(2)_infinite]"
        style={{ imageRendering: 'pixelated' }}
      />
    </div>
  );
}

export default GoblinOpinions;
